In [1]:
import pandas as pn

In [2]:
dataframe = pn.read_csv("UX2-datacollection som csv istedet.csv")
dataframe

  Age;Height;MobileOS
0          20;192;iOS
1      19;189;Android
2      21;186;Android
3      21;184;Android
4      21;194;Android

In [3]:
dataframe.size

5

In [4]:
dataframe.describe()

       Age;Height;MobileOS
count                    5
unique                   5
top             20;192;iOS
freq                     1

In [5]:
# numba fiiiiveehhhh
# Convenience Sampling

In [6]:
# noombur siiiiiiickkssss
# Beacuse it was convenient to sample the people around me (who are the same age group, gender, and stuff) 
# it gave quite similar results